name: Node.js / Python 3 pip GitHub workflow Actions
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        nodejs-version: [12]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} OS, python ${{ matrix.python-version }}, NodeJS ${{ matrix.nodejs-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install / upgrade pip and HTTPie
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --upgrade httpie
      - name: Prepare to CI testing
        run: |
          pip -V
          python -V
          http --version
          node -v
          npm -v
          npm i -E
      - name: Setup scripts and stop in anything is listenning 3000 port
        run: |
          source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
          npm run pm2
          npm run logs &
      - name: Wait for server up and running
        run: wait_for 3000
      - name: Run CI tests
        run: |
          http get :3000/
          http post :3000/maksimko/wtf/ololo
          http post :3000/maksimko/wtf/trololo
      - name: Tear down...
        run: |
          npm stop
          stop_any 3000
